<a href="https://colab.research.google.com/github/NguyenThiMyDuyen129/TH_DeepLearning/blob/main/2001230129_TH_DeepLearning_Tuan01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np

In [46]:
#cách 1
#tạo list
my_list = [1,9,15,39]
print('Python list: ', my_list)

#chuyển list --> numpy array
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]


In [47]:
#cách 2
a = np.array([1,9,15,39])
print(a)

[ 1  9 15 39]


In [48]:
c = np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [49]:
d = np.array([[[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]]])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]]]
(1, 4, 3)


In [50]:
e = np.zeros((2,2))
f = np.ones((3,3))
print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [51]:
e = np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g = np.array([[[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]]])
print(g)
print(g.shape)
h = g.reshape(3,4)
print('reshape (3,4)\n',h)
j = g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k = g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]]]
(1, 4, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


**Bài 1: Tạo mảng 20 số nguyên ngẫu nhiên với kích thước 3x3 có giá trị trong khoảng [0,20]**

In [52]:
a = np.random.randint(0,21,size=(3,3))
print('Mảng ngẫu nhiên (0,20):', a)
if np.all(a!=0):
  print('Mảng khác 0')
else:
  print('Có ít nhất một phần tử bằng 0')

Mảng ngẫu nhiên (0,20): [[17 17 16]
 [ 3  6  2]
 [ 1 10 12]]
Mảng khác 0


**Bài 2: Tạo mảng 20 số nguyên ngẫu nhiên với kích thước 3x3 có giá trị trong khoảng [0,20]**

In [53]:
a = np.random.randint(0,21,size=(3,3))
print('Mảng ngẫu nhiên (0,20):', a)
if np.any(a!=0):
  print('Mảng tồn tại ít nhất 1 phần tử khác 0')
else:
  print('Mảng toàn 0')

Mảng ngẫu nhiên (0,20): [[ 1  7 14]
 [ 3 14 17]
 [18  9 18]]
Mảng tồn tại ít nhất 1 phần tử khác 0


**Bài 3: Tìm hiểu hàm numpy.greater, numpy.greater_equal, numpy.less, numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều**

- numpy.greater (x1, x2) x1 > x2: Kiểm tra phần tử của mảng 1 có lớn hơn mảng 2 không.
- numpy.greater_equal(x1,x2) x1 >= x2: Kiểm tra phần tử của mảng 1 có lớn hơn hoặc bằng mảng 2 không.
- np.less(x1, x2)	x1 < x2: Kiểm tra phần tử của mảng 1 có nhỏ hơn mảng 2 không.
- np.less_equal(x1, x2)	x1 <= x2	Kiểm tra phần tử của mảng 1 có nhỏ hơn hoặc bằng mảng 2 không.

In [54]:
import numpy as np

a = np.array([1, 5, 10])
b = np.array([2, 5, 8])

print("Greater (a > b):      ", np.greater(a, b))
print("Greater Equal (a >= b):", np.greater_equal(a, b))
print("Less (a < b):         ", np.less(a, b))
print("Less Equal (a <= b):   ", np.less_equal(a, b))

Greater (a > b):       [False False  True]
Greater Equal (a >= b): [False  True  True]
Less (a < b):          [ True False False]
Less Equal (a <= b):    [ True  True False]


In [55]:
a = np.array([[1, 10], [20, 30]])
b = np.array([[5, 5], [20, 25]])

# So sánh m1 >= m2
sosanh = np.greater_equal(a, b)

print("Ma trận 1:\n", a)
print("Ma trận 2:\n", b)
print("Kết quả (m1 >= m2):\n", sosanh)

Ma trận 1:
 [[ 1 10]
 [20 30]]
Ma trận 2:
 [[ 5  5]
 [20 25]]
Kết quả (m1 >= m2):
 [[False  True]
 [ True  True]]


**Bài 4: Viết chương trình tạo mảng gần 10 số 1, 10 số 0 và 10 số 5**

In [56]:
a = np.zeros(10)
b = np.ones(10)
#cách 1: dùng np.full
c = np.full(10,5)
#cách 2: dùng np.ones * 5
d = np.ones(10) * 5
ketqua1 = np.concatenate([[a],[b],[c]])
ketqua2 = np.concatenate([[a],[b],[c]])
print('Kết quả 1:', ketqua1)
print('Kích thước mảng: ', ketqua1.size)
print('Kết quả 2:', ketqua2)
print('Kích thước mảng: ', ketqua2.size)

Kết quả 1: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
Kích thước mảng:  30
Kết quả 2: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
Kích thước mảng:  30


**Bài 5: Viết chương trình tạo số nguyên chẵn từ [30, 70]**

In [57]:
# Tạo mảng số nguyên chẵn từ 30 đến 70
# Tham số: start=30, stop=71 (để bao gồm cả số 70), step=2 (để lấy số chẵn)
even_array = np.arange(30,71,2)
print('Dãy số nguyên chẵn [30,70]: ', even_array)

Dãy số nguyên chẵn [30,70]:  [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**Bài 6: Viết chương trình tạo ma trận 3x3 (đường chéo chính = 1, các phần tử còn lại bằng 0)**